### PR TITLE
peni.parker.is.kawaii

### PR DESCRIPTION
**Pull request by JPNYKW**
It's JK pull-request.

### CODE REVIEW

**Comment by JPNYKW** [comment]
Close! C u again, eh, Tenno. XD

**Comment by mongesan** [comment]
wut

**Comment by JPNYKW** [comment]
@mongesan Check it, "spider-man spider-verse"

**Comment by mongesan** [comment]
k

**Comment by kiyotan815** [comment]
0_xmkMflF8JfJ2w8LA

**Comment by JPNYKW** [comment]
@kiyotan815 🤔 🤔 🤔 🤔 🤔 🤔

**Pull request closed without merging**
